const countries = {
    "am-ET": "Amárico (Etiópia)",
    "ar-SA": "Árabe (Arábia Saudita)",
    "be-BY": "Bielorrusso (Bielorrússia)",
    "bem-ZM": "Bemba (Zâmbia)",
    "bi-VU": "Bislamá (Vanuatu)",
    "bjs-BB": "Bajan (Barbados)",
    "bn-IN": "Bengali (Índia)",
    "bo-CN": "Tibetano (China)",
    "br-FR": "Bretão (França)",
    "bs-BA": "Bósnio (Bósnia e Herzegovina)",
    "ca-ES": "Catalão (Espanha)",
    "cop-EG": "Copta (Egito)",
    "cs-CZ": "Tcheco (República Tcheca)",
    "cy-GB": "Galês (Reino Unido)",
    "da-DK": "Dinamarquês (Dinamarca)",
    "dz-BT": "Dzongkha (Butão)",
    "de-DE": "Alemão (Alemanha)",
    "dv-MV": "Maldívio (Maldivas)",
    "el-GR": "Grego (Grécia)",
    "en-GB": "Inglês (Reino Unido)",
    "es-ES": "Espanhol (Espanha)",
    "et-EE": "Estoniano (Estônia)",
    "eu-ES": "Basco (Espanha)",
    "fa-IR": "Persa (Irã)",
    "fi-FI": "Finlandês (Finlândia)",
    "fn-FNG": "Fanagalo",
    "fo-FO": "Feroês (Ilhas Faroé)",
    "fr-FR": "Francês (França)",
    "gl-ES": "Galego (Espanha)",
    "gu-IN": "Gujarati (Índia)",
    "ha-NE": "Hausa (Níger)",
    "he-IL": "Hebraico (Israel)",
    "hi-IN": "Hindi (Índia)",
    "hr-HR": "Croata (Croácia)",
    "hu-HU": "Húngaro (Hungria)",
    "id-ID": "Indonésio (Indonésia)",
    "is-IS": "Islandês (Islândia)",
    "it-IT": "Italiano (Itália)",
    "ja-JP": "Japonês (Japão)",
    "kk-KZ": "Cazaque (Cazaquistão)",
    "km-KM": "Khmer (Comores)",
    "kn-IN": "Canarim (Índia)",
    "ko-KR": "Coreano (Coreia do Sul)",
    "ku-TR": "Curdo (Turquia)",
    "ky-KG": "Quirguiz (Quirguistão)",
    "la-VA": "Latim (Cidade do Vaticano)",
    "lo-LA": "Lao (Laos)",
    "lv-LV": "Letão (Letônia)",
    "men-SL": "Mende (Serra Leoa)",
    "mg-MG": "Malgaxe (Madagáscar)",
    "mi-NZ": "Māori (Nova Zelândia)",
    "ms-MY": "Malaio (Malásia)",
    "mt-MT": "Maltês (Malta)",
    "my-MM": "Birmanês (Mianmar)",
    "ne-NP": "Nepali (Nepal)",
    "niu-NU": "Niuean (Niue)",
    "nl-NL": "Holandês (Países Baixos)",
    "no-NO": "Norueguês (Noruega)",
    "ny-MW": "Nyanja (Malaui)",
    "ur-PK": "Urdu (Paquistão)",
    "pau-PW": "Palauano (Palau)",
    "pa-IN": "Punjabi (Índia)",
    "ps-PK": "Pachto (Paquistão)",
    "pis-SB": "Pijin (Ilhas Salomão)",
    "pl-PL": "Polonês (Polônia)",
    "pt-PT": "Português (Brasil)",
    "rn-BI": "Kirundi (Burundi)",
    "ro-RO": "Romeno (Romênia)",
    "ru-RU": "Russo (Rússia)",
    "sg-CF": "Sango (República Centro-Africana)",
    "si-LK": "Cingalês (Sri Lanka)",
    "sk-SK": "Eslovaco (Eslováquia)",
    "sm-WS": "Samoano (Samoa)",
    "sn-ZW": "Shona (Zimbábue)",
    "so-SO": "Somali (Somália)",
    "sq-AL": "Albanês (Albânia)",
    "sr-RS": "Sérvio (Sérvia)",
    "sv-SE": "Sueco (Suécia)",
    "sw-SZ": "Suaíli (Suazilândia)",
    "ta-LK": "Tâmil (Sri Lanka)",
    "te-IN": "Telugu (Índia)",
    "tet-TL": "Tétum (Timor-Leste)",
    "tg-TJ": "Tajique (Tajiquistão)",
    "th-TH": "Tailandês (Tailândia)",
    "ti-TI": "Tigrínia (Eritreia)",
    "tk-TM": "Turcomano (Turcomenistão)",
    "tl-PH": "Tagalo (Filipinas)",
    "tn-BW": "Tswana (Botsuana)",
    "to-TO": "Tongan (Tonga)",
    "tr-TR": "Turco (Turquia)",
    "uk-UA": "Ucraniano (Ucrânia)",
    "uz-UZ": "Uzbeque (Uzbequistão)",
    "vi-VN": "Vietnamita (Vietnã)",
    "wo-SN": "Wolof (Senegal)",
    "xh-ZA": "Xhosa (África do Sul)",
    "yi-YD": "Yiddish",
    "zu-ZA": "Zulu (África do Sul)"
}
